imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: "%locale%" # 假如用户没有明确表示想要看哪个语言的页面
      # 就认为当前用户是想看%locale%指定语言的页面
    # 用户可通过HTTP请求中的`accept_language`
    # 或者路由里的设置比如`domain.com/zh_CN/home`来指定，可以配置

    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true
    # 注意以下设置的区别：
    translator:
        fallbacks: ["%locale%"] # 如果某个语言没有对应的翻译，就显示fallbacks里的语言翻译



# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: secured_area
    resource_owners:
        qq:
            type: qq
            client_id: 101455664
            client_secret: badfdb86df4a78e0fb3b7ceed70d23f6
    #fosub:
    #    properties:
    #        qq: qqId

    connect: ~


#fos_user:
#    db_driver: orm
#    firewall_name: secured_area
#    user_class: AppBundle\Entity\User

#fos_user:
#    registration:
#        form:
#            type: app_reg

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [JMSTranslationBundle]

jms_translation:
    configs:
        app:
            dirs: ['%kernel.root_dir%/Resources', '%kernel.root_dir%/../src']
            output_dir: '%kernel.root_dir%/Resources/translations'

