# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

  twig.text_extension:
    class: Twig_Extensions_Extension_Text
    tags:
    - name: twig.extension

  app.form.type.reg:
    class: AppBundle\Form\Type\RegType
    argument:
      - %fos_user.model.user.class%
    tags:
      -
        name: form.type
        alias: app_reg